### ISSUE TITLE
Use Django Default Authentication

### ISSUE THREAD

**Issue by ShyamSundhar1411** [AbhijithGanesh/Password-Generator-Django#5]
I went through your code. The logic is fine. But just a suggestion bro just start using Django CBV and Built-in Django Authentication for registration. You don't need any models for that

**Comment by AbhijithGanesh** [comment]
I'll update them Shyam Thank you @ShyamSundhar1411

**Comment by ShyamSundhar1411** [comment]
Can we do a collab ? I am in the same class as yours ?

**Comment by AbhijithGanesh** [comment]
Can I dm ?😅 Discord?

**Comment by ShyamSundhar1411** [comment]
First check my github if you are fine with my projects lets do a collab

**Comment by AbhijithGanesh** [comment]
We'll create an issue and solve it

**Comment by ShyamSundhar1411** [comment]
Sure

**Comment by AbhijithGanesh** [comment]
I am fine with the CBV concept but for registration, we need organization etc, like the simple User model will not fulfil the use case and we need to abstract one more layer

**Comment by AbhijithGanesh** [comment]
@ShyamSundhar1411 can I know how I can reach ya? (If WA may I know if we are in same groups, it'll make things easier)

**Comment by ShyamSundhar1411** [comment]
I am deleting this after a while after you reply to me
